services:
  - type: web
    name: instruction-risk-agent
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    repo: https://github.com/kboltmiller/instruction-risk-agent.git
